# version 3+ does different things re: networking from 2.x
# mainly things to support swarms
# aka things we don't need/want
version: '2.4'
services:
  # httpd
  wiki-web:
    # production: track "prod-nginx" tag on ghcr.io
    image: ghcr.io/wetfish/wiki:prod-nginx
    container_name: wiki-web
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/config.php:/var/www/src/config.php:ro
      - ./config/ban.php:/var/www/src/ban.php:ro
      - ./upload:/var/www/upload:rw
    # join wiki-internal and traefik-backend networks
    networks:
      wiki-internal: {}
      traefik-backend: {}

  # php-fpm
  wiki-php:
    # production: track "prod-php" tag on ghcr.io
    image: ghcr.io/wetfish/wiki:prod-php
    container_name: wiki-php
    restart: unless-stopped
    # db connection info
    env_file:
      - ./php.env
    volumes:
      - ./config/config.php:/var/www/src/config.php:ro
      - ./config/ban.php:/var/www/src/ban.php:ro
      - ./upload:/var/www/upload:rw
      - ./config/php-fpm.conf:/etc/php/5.6/fpm/php-fpm.conf:ro
      - ./config/php-fpm-pool.conf:/etc/php/5.6/fpm/pool.d/www.conf:ro
      - ./config/php.ini:/etc/php/5.6/fpm/php.ini:ro
    networks:
      wiki-internal: {}

  # database
  wiki-db:
    image: docker.io/mariadb:10.10
    container_name: wiki-db
    restart: unless-stopped
    env_file:
      - ./mariadb.env
    command: --sql-mode=""
    volumes:
      - ./config/schema.sql:/docker-entrypoint-initdb.d/setup.sql:ro
      - ./db/data:/var/lib/mysql:rw
    networks:
      wiki-internal: {}

networks:
  # ephemeral, created for us by compose
  wiki-internal:
    driver: bridge
  # persistent, externally created
  traefik-backend:
    external: true
